// <auto-generated />

using EVCharger.Common.Protobuf.DB;
using EVCharger.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EVCharger.DB.Migrations
{
    [DbContext(typeof(ChargerContext))]
    [Migration("20210602202857_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "6.0.0-preview.4.21253.1")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("EVCharger.Base.Models.Models.Charger", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("ChargerStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ConstellationId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConstellationId");

                    b.ToTable("Chargers");
                });

            modelBuilder.Entity("EVCharger.Base.Models.Models.Constellation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AdministratorsId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorsId");

                    b.ToTable("Constellations");
                });

            modelBuilder.Entity("EVCharger.Base.Models.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.Property<string>("ConstellationId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConstellationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EVCharger.Base.Models.Models.Charger", b =>
                {
                    b.HasOne("EVCharger.Base.Models.Models.Constellation", "Constellation")
                        .WithMany()
                        .HasForeignKey("ConstellationId");

                    b.Navigation("Constellation");
                });

            modelBuilder.Entity("EVCharger.Base.Models.Models.Constellation", b =>
                {
                    b.HasOne("EVCharger.Base.Models.Models.User", "Administrators")
                        .WithMany()
                        .HasForeignKey("AdministratorsId");

                    b.Navigation("Administrators");
                });

            modelBuilder.Entity("EVCharger.Base.Models.Models.User", b =>
                {
                    b.HasOne("EVCharger.Base.Models.Models.Constellation", null)
                        .WithMany("Users")
                        .HasForeignKey("ConstellationId");
                });

            modelBuilder.Entity("EVCharger.Base.Models.Models.Constellation", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
