name: Release - Test, Build & Redeploy

on:
  workflow_run:
    workflows: ["Build and Test"]
    branches: [main]
    types: 
      - completed

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Update submodules
        run: git submodule update --recursive --remote   
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build -t markelz0r/evcharger-db:latest ./
      - name: Publish Docker image
        run: docker push markelz0r/evcharger-db:latest
  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}  
